import numpy as np

COMPASS_16_PT = {
    0: "N",
    1: "NNE",
    2: "NE",
    3: "ENE",
    4: "E",
    5: "ESE",
    6: "SE",
    7: "SSE",
    8: "S",
    9: "SSW",
    10: "SW",
    11: "WSW",
    12: "W",
    13: "WNW",
    14: "NW",
    15: "NNW",
    16: "N",
}

WEATHER_TYPES = {
    np.NaN: "Not available",
    0: "Clear night",
    1: "Sunny day",
    2: "Partly cloudy (night)",
    3: "Partly cloudy (day)",
    4: "Not used",
    5: "Mist",
    6: "Fog",
    7: "Cloudy",
    8: "Overcast",
    9: "Light rain shower (night)",
    10: "Light rain shower (day)",
    11: "Drizzle",
    12: "Light rain",
    13: "Heavy rain shower (night)",
    14: "Heavy rain shower (day)",
    15: "Heavy rain",
    16: "Sleet shower (night)",
    17: "Sleet shower (day)",
    18: "Sleet",
    19: "Hail shower (night)",
    20: "Hail shower (day)",
    21: "Hail",
    22: "Light snow shower (night)",
    23: "Light snow shower (day)",
    24: "Light snow",
    25: "Heavy snow shower (night)",
    26: "Heavy snow shower (day)",
    27: "Heavy snow",
    28: "Thunder shower (night)",
    29: "Thunder shower (day)",
    30: "Thunder",
}
# Number is min value for visibility category and the next number is the maximum value
VISIBILITY = {
    0: "Very poor",
    1000: "Poor",
    4000: "Moderate",
    10000: "Good",
    20000: "Very good",
    40000: "Excellent",
}

REGION_TO_COUNTRY = {
    "Central Tayside & Fife": "Scotland",
    "Dumfries, Galloway": "Scotland",
    "East Midlands": "England",
    "East of England": "England",
    "Grampian": "Scotland",
    "Highland & Eilean Siar": "Scotland",
    "London & South East": "England",
    "North East England": "England",
    "North West England": "England",
    "Northern Ireland": "Northern Ireland",
    "Orkney & Shetland": "Scotland",
    "South West England": "England",
    "Strathclyde": "Scotland",
    "Wales": "Wales",
    "West Midlands": "England",
    "Yorkshire & Humber": "England",
    "Isle of Man": "Isle of Man",
}
